#!/bin/sh

set -e

case "${1}" in
	remove)
		if [ -e /usr/share/apache2/apache2-maintscript-helper ]
		then
			. /usr/share/apache2/apache2-maintscript-helper

			apache2_invoke disconf netdata.conf

			apache2_reload restart
		fi
		;;

	purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
